# Generated by Django 5.2.3 on 2025-06-13 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistsubscription',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
